import type { SavedResume } from "./types";

export const MOHAMMED_CV_EN: SavedResume = {
  id: "mohammed-masood-en",
  title: "Mohammed Masood - Kurdish Language Teacher (EN)",
  jobTarget: "Teacher / Educator",
  template: "new-professional",
  createdAt: 1780700000000,
  design: {
    fontFamily: "DM Sans",
    headingFontFamily: "Nunito",
    baseFontSize: 11,
    headingScale: 1.3,
    lineHeight: 1.5,
    letterSpacing: 0,
    accentColor: "#2563eb",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    backgroundColor: "#ffffff",
    sidebarColor: "#f8fafc",
    pagePaddingX: 40,
    pagePaddingY: 45,
    sectionGap: 18,
    itemGap: 10,
    showDividers: true,
    dividerStyle: "solid",
    showSectionIcons: false,
    headerShape: "none",
    bulletStyle: "dot",
    showCanvasDecorations: false,
    canvasDecorationStyle: "none",
    showSkillBars: true,
    skillBarStyle: "lines",
    skillsLocation: "sidebar",
    skillsColumns: 1,
    photoShape: "rounded",
    photoSize: 90,
    columnLayout: "sidebar-left",
    contentOrder: ["profile", "experience", "skills", "education", "languages", "certifications"],
  },
  data: {
    name: "Mohammed Masood Rashid",
    photoUrl: "",
    title: "Kurdish Language Teacher",
    phone: "0750 887 03 94",
    email: "",
    location: "Shawes, Erbil, Iraq",
    summary: "A dedicated and highly motivated teacher holding a degree from the College of Basic Education (Kurdish Department), with proven experience teaching students from 1st to 9th grade. Possesses specialized expertise in delivering comprehensive and engaging Kurdish language curricula, alongside practical experience in management and teaching 7th grade. Offers a unique blend of teaching and team leadership skills. Highly adaptable and organized, committed to fostering an environment where students and collaborative teams can thrive.",
    experience: [
      {
        title: "Kurdish Language Teacher",
        company: "Erbil, Iraq",
        duration: "Recent",
        description: "Designed and delivered comprehensive Kurdish language lessons for students in grades 1 through 9, ensuring alignment with educational standards.",
        achievements: [
          "Spearheaded specialized teaching for 7th-grade students, developing targeted lesson plans suited to their academic and developmental needs.",
          "Monitored and evaluated student progress through exams, quizzes, and daily assignments, providing constructive feedback to encourage continuous improvement.",
          "Cultivated a positive, inclusive, and organized classroom environment that fostered student participation and interaction.",
          "Collaborated with fellow teachers and school administration to enhance teaching strategies and elevate student performance."
        ],
      },
      {
        title: "Market Manager",
        company: "Erbil, Iraq",
        duration: "Previous",
        description: "Led a dedicated team by organizing daily schedules, delegating tasks, and fostering a collaborative work environment.",
        achievements: [
          "Trained and mentored new team members, ensuring high performance standards and clear communication across the group.",
          "Managed organizational resources and supplies, demonstrating strong logistics planning and problem-solving skills.",
          "Served as a key point of contact for resolving issues and ensuring smooth, organized, and positive daily operations."
        ],
      },
    ],
    languages: [
      "Kurdish (Native)",
      "Arabic (Good)",
    ],
    projects: [],
    education: [
      {
        degree: "Bachelor's Degree in Basic Education (Kurdish Department)",
        institution: "College of Basic Education",
        year: "Graduated",
      },
    ],
    skills: [
      "Classroom Management",
      "Lesson Planning",
      "Student Assessment",
      "Differentiated Instruction",
      "Team Coordination",
      "Parent-Teacher Communication",
      "Resource Management",
    ],
    skillItems: [
      { name: "Classroom Management", level: 5 },
      { name: "Lesson Planning", level: 5 },
      { name: "Student Assessment", level: 4 },
      { name: "Team Coordination", level: 5 },
      { name: "Parent-Teacher Communication", level: 4 },
      { name: "Resource Management", level: 4 },
    ],
    certifications: [
      "Date of Birth: 14/10/2002",
      "Nationality: Iraqi",
      "Marital Status: Single"
    ],
    sectionTitles: {
      profile: "Professional Summary",
      experience: "Work Experience",
      education: "Education",
      skills: "Core Competencies",
      languages: "Languages",
      certifications: "Personal Info",
    },
  },
};

export const MOHAMMED_CV_KU: SavedResume = {
  id: "mohammed-masood-ku",
  title: "محەممەد مەسعود ڕەشید - سیڤی مامۆستا (KU)",
  jobTarget: "مامۆستا",
  template: "new-professional",
  createdAt: 1780700000001,
  design: {
    fontFamily: "DM Sans",
    headingFontFamily: "Nunito",
    baseFontSize: 11,
    headingScale: 1.3,
    lineHeight: 1.5,
    letterSpacing: 0,
    accentColor: "#2563eb",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    backgroundColor: "#ffffff",
    sidebarColor: "#f8fafc",
    pagePaddingX: 40,
    pagePaddingY: 45,
    sectionGap: 18,
    itemGap: 10,
    showDividers: true,
    dividerStyle: "solid",
    showSectionIcons: false,
    headerShape: "none",
    bulletStyle: "dot",
    showCanvasDecorations: false,
    canvasDecorationStyle: "none",
    showSkillBars: true,
    skillBarStyle: "lines",
    skillsLocation: "sidebar",
    skillsColumns: 1,
    photoShape: "rounded",
    photoSize: 90,
    columnLayout: "sidebar-left",
    contentOrder: ["profile", "experience", "skills", "education", "languages", "certifications"],
  },
  data: {
    name: "محەممەد مەسعود ڕەشید",
    photoUrl: "",
    title: "مامۆستای زمانی کوردی",
    phone: "0750 887 03 94",
    email: "",
    location: "شاوێس، هەولێر، عێراق",
    summary: "مامۆستایەکی دڵسۆز و خاوەن پاڵنەرێکی بەهێز، هەڵگری بڕوانامەی کۆلێژی پەروەردەی بنەڕەتییە (بەشی کوردی)، خاوەنی ئەزموونێکی سەلمێندراوە لە وانەوتنەوە بە قوتابیان لە پۆلی یەکەمەوە تا نۆیەم. شارەزایی تایبەتی هەیە لە پێشکەشکردنی پرۆگرامی خوێندنی زمانی کوردی بە شێوەیەکی سەرنجڕاکێش و گشتگیر، لەگەڵ هەبوونی ئەزموونی پراکتیکی تایبەت بە بەڕێوەبردن و وانەوتنەوە لە پۆلی حەوتەم. خاوەنی تێکەڵەیەکی ناوازەیە لە کارامەییەکانی وانەوتنەوە و سەرکردایەتیکردنی تیم. کەسێکی گونجاو و ڕێکخراوە، وە پابەندە بە ڕەخساندنی ژینگەیەک کە تێیدا قوتابیان و تیمە هاوبەشەکان بتوانن گەشە بکەن.",
    experience: [
      {
        title: "مامۆستای زمانی کوردی",
        company: "هەولێر، عێراق",
        duration: "لەم دواییانەدا",
        description: "داڕشتن و پێشکەشکردنی وانەی گشتگیری زمانی کوردی بۆ قوتابیانی پۆلی یەکەم تا نۆیەم، بە دڵنیابوون لە گونجانیان لەگەڵ ستانداردە پەروەردەییەکان.",
        achievements: [
          "پێشەنگایەتیکردنی وانەوتنەوەی تایبەت بە قوتابیانی پۆلی حەوتەم، لەگەڵ پەرەپێدانی پلانی وانەوتنەوەی ئامانجدار کە لەگەڵ پێداویستییە ئەکادیمی و گەشەسەندنەکانیان دەگونجێت.",
          "چاودێریکردن و هەڵسەنگاندنی ئاستی پێشکەوتنی قوتابیان لە ڕێگەی تاقیکردنەوە، کویز و ئەرکەکانی ڕۆژانە، لەگەڵ پێدانی فیدباکی بنیاتنەر بۆ هاندانی بەرەوپێشچوونی بەردەوام.",
          "ڕەخساندنی ژینگەیەکی پۆلی ئەرێنی، گشتگیر و ڕێکخراو کە هانی بەشداریکردن و کارلێکی قوتابیان دەدات.",
          "هاوکاریکردن لەگەڵ مامۆستایانی تر و کارگێڕی قوتابخانە بۆ باشترکردنی ستراتیژییەکانی فێرکردن و ئاستی قوتابیان."
        ],
      },
      {
        title: "بەڕێوەبەری مارکێت",
        company: "هەولێر، عێراق",
        duration: "پێشتر",
        description: "سەرکردایەتیکردنی تیمێکی دڵسۆز لە ڕێگەی ڕێکخستنی خشتەی ڕۆژانە، دابەشکردنی ئەرکەکان، و ڕەخساندنی ژینگەیەکی کاری هاوبەش.",
        achievements: [
          "ڕاهێنان و ڕێنماییکردنی ئەندامە نوێیەکانی تیمەکە، بۆ دڵنیابوون لە ئاستی بەرزی کارکردن و پەیوەندی ڕوون لە نێوان گرووپەکەدا.",
          "بەڕێوەبردنی سەرچاوە و پێداویستییەکانی ڕێکخراوەکە، بە نیشاندانی کارامەیی بەهێز لە پلاندانانی لۆجستی و چارەسەرکردنی کێشەکان.",
          "کەسایەتی سەرەکی بووە بۆ چارەسەرکردنی کێشەکان و دڵنیابوون لە بەڕێوەچوونی کارەکانی ڕۆژانە بە شێوەیەکی ڕێکخراو و ئەرێنی."
        ],
      },
    ],
    languages: [
      "کوردی (زمانی دایک)",
      "عەرەبی (باشە)",
    ],
    projects: [],
    education: [
      {
        degree: "دەرچووی کۆلێژی پەروەردەی بنەڕەتی (بەشی کوردی)",
        institution: "کۆلێژی پەروەردەی بنەڕەتی",
        year: "دەرچوو",
      },
    ],
    skills: [
      "بەڕێوەبردنی پۆل",
      "داڕشتنی پلانی وانەوتنەوە",
      "هەڵسەنگاندنی قوتابیان",
      "فێرکردنی هەمەجۆر",
      "هەماهەنگی تیم",
      "پەیوەندی نێوان مامۆستا و باوان",
      "بەڕێوەبردنی سەرچاوەکان",
    ],
    skillItems: [
      { name: "بەڕێوەبردنی پۆل", level: 5 },
      { name: "داڕشتنی پلانی وانەوتنەوە", level: 5 },
      { name: "هەڵسەنگاندنی قوتابیان", level: 4 },
      { name: "هەماهەنگی تیم", level: 5 },
      { name: "پەیوەندی نێوان مامۆستا و باوان", level: 4 },
      { name: "بەڕێوەبردنی سەرچاوەکان", level: 4 },
    ],
    certifications: [
      "بەرواری لەدایکبوون: ١٤/١٠/٢٠٠٢",
      "ڕەگەزنامە: عێراقی",
      "باری خێزانی: سەڵت"
    ],
    sectionTitles: {
      profile: "پوختەی پیشەیی",
      experience: "ئەزموونی پیشەیی",
      education: "بڕوانامە",
      skills: "توانا و لێهاتووییە سەرەکییەکان",
      languages: "زمانەکان",
      certifications: "زانیاری کەسی",
    },
  },
};

export const AHMAD_CV_EN: SavedResume = {
  id: "ahmad-masoud-en",
  title: "Ahmad Masoud - Mall Staff (EN)",
  jobTarget: "Mall Assistant / Retail",
  template: "new-professional",
  createdAt: 1780800000000,
  design: {
    fontFamily: "Inter",
    headingFontFamily: "Outfit",
    baseFontSize: 11,
    headingScale: 1.2,
    lineHeight: 1.5,
    letterSpacing: 0,
    accentColor: "#111827",
    textColor: "#374151",
    headingColor: "#111827",
    backgroundColor: "#ffffff",
    sidebarColor: "#f3f4f6",
    pagePaddingX: 40,
    pagePaddingY: 45,
    sectionGap: 18,
    itemGap: 10,
    showDividers: true,
    dividerStyle: "solid",
    showSectionIcons: false,
    headerShape: "none",
    bulletStyle: "dot",
    showCanvasDecorations: false,
    canvasDecorationStyle: "none",
    showSkillBars: true,
    skillBarStyle: "lines",
    skillsLocation: "sidebar",
    skillsColumns: 1,
    photoShape: "rounded",
    photoSize: 90,
    columnLayout: "sidebar-left",
    contentOrder: ["profile", "experience", "skills", "education", "languages", "certifications"],
  },
  data: {
    name: "Ahmad Masoud Rashed",
    photoUrl: "",
    title: "Mall Assistant & Customer Service",
    phone: "",
    email: "",
    location: "Shawes, Erbil, Iraq",
    summary: "A highly motivated and hardworking university student with hands-on experience in customer-facing roles. Eager to bring my energy, strong work ethic, and quick learning abilities to a dynamic retail or mall environment. Proficient in computer applications and dedicated to providing excellent customer service and maintaining smooth daily operations.",
    experience: [
      {
        title: "Print & Copy Shop Assistant",
        company: "Erbil, Iraq",
        duration: "Previous",
        description: "Operated printing and copying machinery efficiently, serving a high volume of daily customers.",
        achievements: [
          "Welcomed customers and successfully fulfilled their specific printing and document preparation requests.",
          "Utilized computer programs including MS Word, Excel, and Photoshop to format, edit, and prepare files for printing.",
          "Maintained organized records and ensured equipment was running smoothly."
        ],
      },
      {
        title: "Supermarket Staff",
        company: "Erbil, Iraq",
        duration: "Previous",
        description: "Assisted in daily supermarket operations, ensuring a clean and welcoming environment for shoppers.",
        achievements: [
          "Organized merchandise accurately on shelves and managed inventory displays.",
          "Assisted customers in finding products, demonstrating strong interpersonal and customer service skills.",
          "Worked fast and reliably as part of a dedicated team during busy shopping hours."
        ],
      },
    ],
    languages: [
      "Kurdish (Native)",
      "English (Basic)",
      "Arabic (Basic)",
    ],
    projects: [],
    education: [
      {
        degree: "University Student",
        institution: "Erbil",
        year: "Current",
      },
      {
        degree: "High School Graduate",
        institution: "Shawes",
        year: "Graduated",
      }
    ],
    skills: [
      "MS Word, Excel, PPT",
      "Adobe Photoshop",
      "Customer Service",
      "Hardworking",
      "Teamwork",
    ],
    skillItems: [
      { name: "MS Office Suite", level: 4 },
      { name: "Adobe Photoshop", level: 3 },
      { name: "Customer Service", level: 5 },
      { name: "Teamwork", level: 5 },
    ],
    certifications: [
      "Year of Birth: 2007",
      "Location: Shawes, Erbil"
    ],
    sectionTitles: {
      profile: "Profile",
      experience: "Experience",
      education: "Education",
      skills: "Skills",
      languages: "Languages",
      certifications: "Personal Info",
    },
  },
};

export const AHMAD_CV_KU: SavedResume = {
  id: "ahmad-masoud-ku",
  title: "ئەحمەد مەسعود ڕەشید - ستافی مۆڵ (KU)",
  jobTarget: "ستافی مۆڵ / فرۆشیار",
  template: "new-professional",
  createdAt: 1780800000001,
  design: {
    fontFamily: "Inter",
    headingFontFamily: "Outfit",
    baseFontSize: 11,
    headingScale: 1.2,
    lineHeight: 1.5,
    letterSpacing: 0,
    accentColor: "#111827",
    textColor: "#374151",
    headingColor: "#111827",
    backgroundColor: "#ffffff",
    sidebarColor: "#f3f4f6",
    pagePaddingX: 40,
    pagePaddingY: 45,
    sectionGap: 18,
    itemGap: 10,
    showDividers: true,
    dividerStyle: "solid",
    showSectionIcons: false,
    headerShape: "none",
    bulletStyle: "dot",
    showCanvasDecorations: false,
    canvasDecorationStyle: "none",
    showSkillBars: true,
    skillBarStyle: "lines",
    skillsLocation: "sidebar",
    skillsColumns: 1,
    photoShape: "rounded",
    photoSize: 90,
    columnLayout: "sidebar-left",
    contentOrder: ["profile", "experience", "skills", "education", "languages", "certifications"],
  },
  data: {
    name: "ئەحمەد مەسعود ڕەشید",
    photoUrl: "",
    title: "کارمەندی مۆڵ و خزمەتگوزاری کڕیار",
    phone: "",
    email: "",
    location: "شاوێس، هەولێر",
    summary: "گەنجێکی ماندوونەناس و پڕ وزە، قوتابی زانکۆم و خاوەنی ئەزموونی پراکتیکیم لە مامەڵەکردن لەگەڵ کڕیاران و کارکردن لە ژینگەی خێرا. ئامانجمە بە وزە و تواناکانمەوە، و بە سوودوەرگرتن لە شارەزاییم لە بەکارهێنانی کۆمپیوتەر و کاری تیمیدا، خزمەتێکی باش پێشکەش بە مۆڵ یان فرۆشگاکە بکەم.",
    experience: [
      {
        title: "کارمەندی چاپەمەنی و استینساخ",
        company: "هەولێر",
        duration: "پێشتر",
        description: "بەڕێوەبردنی ئامێرەکانی چاپکردن و کۆپیکردن و پێشکەشکردنی خزمەتگوزاری بە ژمارەیەکی زۆر لە کڕیاران لە ڕۆژێکدا.",
        achievements: [
          "پێشوازیکردن لە کڕیاران و جێبەجێکردنی داواکارییەکانیان بە خێرایی و وردی.",
          "بەکارهێنانی بەرنامەکانی کۆمپیوتەر (وەک وۆرد، ئێکسڵ، پاوەرپۆینت، فۆتۆشۆپ) بۆ ڕێکخستن و ئامادەکردنی فایلەکان پێش چاپکردن.",
          "ڕێکخستن و پاراستنی ئامێرەکان و دڵنیابوونەوە لە کارکردنیان بە باشی."
        ],
      },
      {
        title: "کارمەندی سوپەرمارکێت",
        company: "هەولێر",
        duration: "پێشتر",
        description: "هاوکاریکردن لە کارەکانی ڕۆژانەی سوپەرمارکێت و دڵنیابوونەوە لە خاوێنی و ڕێکخستنی شوێنی کار.",
        achievements: [
          "ڕێکخستنی کاڵاکان لەسەر ڕەفەکان بە شێوەیەکی سەرنجڕاکێش و ڕێکوپێک.",
          "هاوکاریکردنی کڕیاران بۆ دۆزینەوەی پێداویستییەکانیان و وەڵامدانەوەی پرسیارەکانیان بە ڕوویەکی خۆشەوە.",
          "کارکردن بە شێوەیەکی خێرا و ماندوونەناسانە لەگەڵ تیمی کارکردن، بەتایبەتی لە کاتە جەنجاڵەکاندا."
        ],
      },
    ],
    languages: [
      "کوردی (زمانی دایک)",
      "ئینگلیزی (سەرەتایی)",
      "عەرەبی (سەرەتایی)",
    ],
    projects: [],
    education: [
      {
        degree: "قوتابی زانکۆ",
        institution: "هەولێر",
        year: "لە ئێستادا",
      },
      {
        degree: "دەرچووی ئامادەیی",
        institution: "شاوێس",
        year: "دەرچوو",
      }
    ],
    skills: [
      "بەرنامەکانی ئۆفیس (Word, Excel, PPT)",
      "فۆتۆشۆپ (Photoshop)",
      "مامەڵەکردنی باش لەگەڵ کڕیار",
      "ماندوونەناس و دڵسۆز",
      "کاری هەرەوەزی (تیم)",
    ],
    skillItems: [
      { name: "بەرنامەکانی ئۆفیس", level: 4 },
      { name: "فۆتۆشۆپ", level: 3 },
      { name: "خزمەتگوزاری کڕیار", level: 5 },
      { name: "کاری تیم", level: 5 },
    ],
    certifications: [
      "ساڵی لەدایکبوون: 2007",
      "شوێنی نیشتەجێبوون: شاوێس، هەولێر"
    ],
    sectionTitles: {
      profile: "پوختە",
      experience: "ئەزموون",
      education: "خوێندن",
      skills: "لێهاتووییەکان",
      languages: "زمانەکان",
      certifications: "زانیاری کەسی",
    },
  },
};

// Export fallback to prevent missing import errors
export const MANSUR_CV = MOHAMMED_CV_KU;
