/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SignupSplatRouteImport } from './routes/signup.$'
import { Route as LoginSplatRouteImport } from './routes/login.$'
import { Route as EditorIdRouteImport } from './routes/editor.$id'
import { Route as DashboardThanksRouteImport } from './routes/dashboard.thanks'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardMyCvsRouteImport } from './routes/dashboard.my-cvs'
import { Route as DashboardJobTrackerRouteImport } from './routes/dashboard.job-tracker'
import { Route as DashboardJobAgentRouteImport } from './routes/dashboard.job-agent'
import { Route as DashboardCoverLettersRouteImport } from './routes/dashboard.cover-letters'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAiWriterRouteImport } from './routes/dashboard.ai-writer'
import { Route as DashboardAiOptimizeRouteImport } from './routes/dashboard.ai-optimize'
import { Route as ApiHeartbeatRouteImport } from './routes/api.heartbeat'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SignupSplatRoute = SignupSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignupRoute,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LoginRoute,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardThanksRoute = DashboardThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyCvsRoute = DashboardMyCvsRouteImport.update({
  id: '/my-cvs',
  path: '/my-cvs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobTrackerRoute = DashboardJobTrackerRouteImport.update({
  id: '/job-tracker',
  path: '/job-tracker',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobAgentRoute = DashboardJobAgentRouteImport.update({
  id: '/job-agent',
  path: '/job-agent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoverLettersRoute = DashboardCoverLettersRouteImport.update({
  id: '/cover-letters',
  path: '/cover-letters',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiWriterRoute = DashboardAiWriterRouteImport.update({
  id: '/ai-writer',
  path: '/ai-writer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiOptimizeRoute = DashboardAiOptimizeRouteImport.update({
  id: '/ai-optimize',
  path: '/ai-optimize',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiHeartbeatRoute = ApiHeartbeatRouteImport.update({
  id: '/api/heartbeat',
  path: '/api/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/heartbeat': typeof ApiHeartbeatRoute
  '/dashboard/ai-optimize': typeof DashboardAiOptimizeRoute
  '/dashboard/ai-writer': typeof DashboardAiWriterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/cover-letters': typeof DashboardCoverLettersRoute
  '/dashboard/job-agent': typeof DashboardJobAgentRoute
  '/dashboard/job-tracker': typeof DashboardJobTrackerRoute
  '/dashboard/my-cvs': typeof DashboardMyCvsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/thanks': typeof DashboardThanksRoute
  '/editor/$id': typeof EditorIdRoute
  '/login/$': typeof LoginSplatRoute
  '/signup/$': typeof SignupSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/heartbeat': typeof ApiHeartbeatRoute
  '/dashboard/ai-optimize': typeof DashboardAiOptimizeRoute
  '/dashboard/ai-writer': typeof DashboardAiWriterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/cover-letters': typeof DashboardCoverLettersRoute
  '/dashboard/job-agent': typeof DashboardJobAgentRoute
  '/dashboard/job-tracker': typeof DashboardJobTrackerRoute
  '/dashboard/my-cvs': typeof DashboardMyCvsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/thanks': typeof DashboardThanksRoute
  '/editor/$id': typeof EditorIdRoute
  '/login/$': typeof LoginSplatRoute
  '/signup/$': typeof SignupSplatRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/heartbeat': typeof ApiHeartbeatRoute
  '/dashboard/ai-optimize': typeof DashboardAiOptimizeRoute
  '/dashboard/ai-writer': typeof DashboardAiWriterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/cover-letters': typeof DashboardCoverLettersRoute
  '/dashboard/job-agent': typeof DashboardJobAgentRoute
  '/dashboard/job-tracker': typeof DashboardJobTrackerRoute
  '/dashboard/my-cvs': typeof DashboardMyCvsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/thanks': typeof DashboardThanksRoute
  '/editor/$id': typeof EditorIdRoute
  '/login/$': typeof LoginSplatRoute
  '/signup/$': typeof SignupSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/interview'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/templates'
    | '/terms'
    | '/verify-email'
    | '/api/heartbeat'
    | '/dashboard/ai-optimize'
    | '/dashboard/ai-writer'
    | '/dashboard/analytics'
    | '/dashboard/cover-letters'
    | '/dashboard/job-agent'
    | '/dashboard/job-tracker'
    | '/dashboard/my-cvs'
    | '/dashboard/settings'
    | '/dashboard/thanks'
    | '/editor/$id'
    | '/login/$'
    | '/signup/$'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/interview'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/templates'
    | '/terms'
    | '/verify-email'
    | '/api/heartbeat'
    | '/dashboard/ai-optimize'
    | '/dashboard/ai-writer'
    | '/dashboard/analytics'
    | '/dashboard/cover-letters'
    | '/dashboard/job-agent'
    | '/dashboard/job-tracker'
    | '/dashboard/my-cvs'
    | '/dashboard/settings'
    | '/dashboard/thanks'
    | '/editor/$id'
    | '/login/$'
    | '/signup/$'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/interview'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/templates'
    | '/terms'
    | '/verify-email'
    | '/api/heartbeat'
    | '/dashboard/ai-optimize'
    | '/dashboard/ai-writer'
    | '/dashboard/analytics'
    | '/dashboard/cover-letters'
    | '/dashboard/job-agent'
    | '/dashboard/job-tracker'
    | '/dashboard/my-cvs'
    | '/dashboard/settings'
    | '/dashboard/thanks'
    | '/editor/$id'
    | '/login/$'
    | '/signup/$'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InterviewRoute: typeof InterviewRoute
  LoginRoute: typeof LoginRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiHeartbeatRoute: typeof ApiHeartbeatRoute
  EditorIdRoute: typeof EditorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/signup/$': {
      id: '/signup/$'
      path: '/$'
      fullPath: '/signup/$'
      preLoaderRoute: typeof SignupSplatRouteImport
      parentRoute: typeof SignupRoute
    }
    '/login/$': {
      id: '/login/$'
      path: '/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof LoginRoute
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/thanks': {
      id: '/dashboard/thanks'
      path: '/thanks'
      fullPath: '/dashboard/thanks'
      preLoaderRoute: typeof DashboardThanksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-cvs': {
      id: '/dashboard/my-cvs'
      path: '/my-cvs'
      fullPath: '/dashboard/my-cvs'
      preLoaderRoute: typeof DashboardMyCvsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/job-tracker': {
      id: '/dashboard/job-tracker'
      path: '/job-tracker'
      fullPath: '/dashboard/job-tracker'
      preLoaderRoute: typeof DashboardJobTrackerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/job-agent': {
      id: '/dashboard/job-agent'
      path: '/job-agent'
      fullPath: '/dashboard/job-agent'
      preLoaderRoute: typeof DashboardJobAgentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cover-letters': {
      id: '/dashboard/cover-letters'
      path: '/cover-letters'
      fullPath: '/dashboard/cover-letters'
      preLoaderRoute: typeof DashboardCoverLettersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-writer': {
      id: '/dashboard/ai-writer'
      path: '/ai-writer'
      fullPath: '/dashboard/ai-writer'
      preLoaderRoute: typeof DashboardAiWriterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-optimize': {
      id: '/dashboard/ai-optimize'
      path: '/ai-optimize'
      fullPath: '/dashboard/ai-optimize'
      preLoaderRoute: typeof DashboardAiOptimizeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/heartbeat': {
      id: '/api/heartbeat'
      path: '/api/heartbeat'
      fullPath: '/api/heartbeat'
      preLoaderRoute: typeof ApiHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiOptimizeRoute: typeof DashboardAiOptimizeRoute
  DashboardAiWriterRoute: typeof DashboardAiWriterRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCoverLettersRoute: typeof DashboardCoverLettersRoute
  DashboardJobAgentRoute: typeof DashboardJobAgentRoute
  DashboardJobTrackerRoute: typeof DashboardJobTrackerRoute
  DashboardMyCvsRoute: typeof DashboardMyCvsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardThanksRoute: typeof DashboardThanksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiOptimizeRoute: DashboardAiOptimizeRoute,
  DashboardAiWriterRoute: DashboardAiWriterRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCoverLettersRoute: DashboardCoverLettersRoute,
  DashboardJobAgentRoute: DashboardJobAgentRoute,
  DashboardJobTrackerRoute: DashboardJobTrackerRoute,
  DashboardMyCvsRoute: DashboardMyCvsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardThanksRoute: DashboardThanksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LoginRouteChildren {
  LoginSplatRoute: typeof LoginSplatRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginSplatRoute: LoginSplatRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface SignupRouteChildren {
  SignupSplatRoute: typeof SignupSplatRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupSplatRoute: SignupSplatRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InterviewRoute: InterviewRoute,
  LoginRoute: LoginRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiHeartbeatRoute: ApiHeartbeatRoute,
  EditorIdRoute: EditorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
