/** MemoryCV-branded Clerk auth UI — social OAuth on top, no Clerk logo/footer. */
export const memoryCvClerkAppearance = {
  layout: {
    logoPlacement: "none" as const,
    socialButtonsPlacement: "top" as const,
    socialButtonsVariant: "blockButton" as const,
    showOptionalFields: true,
  },
  variables: {
    colorPrimary: "#2563eb",
    colorText: "#0f172a",
    colorTextSecondary: "#64748b",
    colorBackground: "transparent",
    colorInputBackground: "#f8fafc",
    colorInputText: "#0f172a",
    colorNeutral: "#94a3b8",
    borderRadius: "0.875rem",
    fontFamily: '"DM Sans", system-ui, sans-serif',
    fontSize: "0.9rem",
    spacingUnit: "1rem",
  },
  elements: {
    rootBox: "w-full",
    card: "shadow-none border-0 p-0 bg-transparent w-full",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    logoBox: "hidden",
    logoImage: "hidden",
    footer: "hidden",
    footerPages: "hidden",
    footerAction: "hidden",
    socialButtonsRoot: "w-full flex flex-col gap-2.5",
    socialButtonsBlockButton:
      "w-full flex items-center justify-center gap-2.5 rounded-xl border border-[#e2e8f0] bg-white py-2.5 px-4 text-sm font-semibold text-[#0f172a] shadow-sm transition-all duration-150 hover:bg-slate-50 hover:border-[#cbd5e1] hover:shadow-md",
    socialButtonsBlockButtonText: "font-semibold tracking-[-0.01em]",
    socialButtonsProviderIcon: "h-[18px] w-[18px]",
    dividerRow: "my-4",
    dividerLine: "bg-[#e2e8f0]",
    dividerText: "text-xs text-[#94a3b8] uppercase tracking-widest font-medium px-2",
    form: "flex flex-col gap-3",
    formFieldLabel: "text-xs font-semibold text-[#475569] tracking-wide mb-0.5",
    formFieldInput:
      "rounded-xl border border-[#e2e8f0] bg-[#f8fafc] px-4 py-2.5 text-sm text-[#0f172a] shadow-none outline-none transition-all duration-150 placeholder:text-[#94a3b8] focus:border-[#2563eb] focus:ring-2 focus:ring-[#2563eb]/15",
    formButtonPrimary:
      "rounded-xl bg-[#2563eb] py-2.5 px-4 text-sm font-semibold text-white shadow-[0_2px_12px_-2px_rgba(37,99,235,0.45)] transition-all duration-150 hover:bg-[#1d4ed8] hover:shadow-[0_4px_16px_-2px_rgba(37,99,235,0.55)] active:scale-[0.99]",
    footerActionLink: "font-semibold text-[#2563eb] underline-offset-2 hover:underline",
    identityPreviewEditButton: "text-[#2563eb] text-xs font-medium",
    badge: "hidden",
    formFieldRow: "gap-1",
    alert: "rounded-xl border border-[#fecaca] bg-[#fef2f2] text-xs text-[#ef4444] px-3 py-2",
    alertText: "text-xs text-[#dc2626]",
    formResendCodeLink: "text-[#2563eb] text-xs font-medium underline-offset-2 hover:underline",
    otpCodeFieldInput:
      "rounded-xl border border-[#e2e8f0] bg-[#f8fafc] text-center text-lg font-bold text-[#0f172a] shadow-none outline-none transition-all duration-150 focus:border-[#2563eb] focus:ring-2 focus:ring-[#2563eb]/15 w-10 h-12",
  },
};
