/** MemoryCV-branded Clerk auth UI — Linear/Figma-grade, no Clerk chrome. */
export const memoryCvClerkAppearance = {
  layout: {
    logoPlacement: "none" as const,
    socialButtonsPlacement: "top" as const,
    socialButtonsVariant: "blockButton" as const,
    showOptionalFields: true,
  },
  variables: {
    colorPrimary: "#0A0B10",
    colorText: "#0f172a",
    colorTextSecondary: "#64748b",
    colorBackground: "transparent",
    colorInputBackground: "#ffffff",
    colorDanger: "#e11d48",
    borderRadius: "0.625rem",
    fontFamily: '"DM Sans", system-ui, sans-serif',
    fontSize: "14px",
  },
  elements: {
    rootBox: "w-full",
    card: "shadow-none border-0 p-0 bg-transparent w-full gap-4",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    logoBox: "hidden",
    logoImage: "hidden",
    footer: "hidden",
    footerPages: "hidden",
    footerAction: "hidden",
    main: "gap-4",
    socialButtonsRoot: "w-full gap-2",
    socialButtonsBlockButton:
      "w-full rounded-lg border border-slate-200 bg-white py-2.5 text-[13.5px] font-medium text-slate-900 shadow-[0_1px_2px_rgba(15,23,42,0.04)] transition-all hover:border-slate-300 hover:bg-slate-50",
    socialButtonsBlockButtonText: "font-medium",
    socialButtonsProviderIcon: "h-[18px] w-[18px]",
    dividerRow: "my-1",
    dividerLine: "bg-slate-200",
    dividerText: "text-[10.5px] font-medium text-slate-400 uppercase tracking-[0.14em] px-3",
    form: "gap-3.5",
    formFieldRow: "gap-1.5",
    formFieldLabel: "text-[12px] font-medium text-slate-700",
    formFieldInput:
      "rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-[14px] text-slate-900 shadow-[0_1px_2px_rgba(15,23,42,0.03)] focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10 focus:outline-none transition",
    formFieldInputShowPasswordButton: "text-slate-400 hover:text-slate-700",
    formButtonPrimary:
      "rounded-lg bg-slate-900 py-2.5 text-[13.5px] font-semibold text-white shadow-[0_1px_2px_rgba(15,23,42,0.2),inset_0_1px_0_rgba(255,255,255,0.08)] transition hover:bg-slate-800 focus:ring-2 focus:ring-slate-900/20 focus:outline-none",
    formFieldAction: "text-[12px] font-medium text-slate-900 hover:underline",
    identityPreview: "rounded-lg border border-slate-200 bg-white",
    identityPreviewEditButton: "text-slate-900",
    otpCodeFieldInput:
      "rounded-lg border border-slate-200 bg-white text-slate-900 focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10",
    formResendCodeLink: "text-slate-900 hover:underline",
    alert: "rounded-lg border border-rose-200 bg-rose-50 text-rose-900 text-[13px]",
    alertText: "text-rose-900",
    badge: "hidden",
  },
};
